SELECT
    T1.AUTHOR_ID
    , T2.AUTHOR_NAME
    , T1.CATEGORY
    , SUM(T1.TOTAL_SALES)
FROM
    (
    SELECT
        T1.BOOK_ID
        , T1.CATEGORY
        , T1.AUTHOR_ID
        , T2.SALES
        , T1.PRICE * T2.SALES AS TOTAL_SALES
    FROM
        BOOK T1
        JOIN BOOK_SALES T2 ON T1.BOOK_ID = T2.BOOK_ID
    WHERE 1 = 1
        AND DATE_FORMAT(T2.SALES_DATE, "%Y-%m") = "2022-01"
    ) T1
    JOIN AUTHOR T2
    ON T1.AUTHOR_ID = T2.AUTHOR_ID  
GROUP BY
    T2.AUTHOR_ID
    , T1.CATEGORY
ORDER BY
    T2.AUTHOR_ID ASC
    , T1.CATEGORY DESC