SELECT
    T2.USER_ID
    , T2.NICKNAME
    , T1.TOTAL_PRICE
FROM
    (
    SELECT
        WRITER_ID
        , SUM(PRICE) AS TOTAL_PRICE
    FROM    
        USED_GOODS_BOARD
    WHERE 1 = 1
        AND STATUS = 'DONE'
    GROUP BY
        WRITER_ID    
    ) T1
    JOIN USED_GOODS_USER T2
    ON T1.WRITER_ID = T2.USER_ID
    AND TOTAL_PRICE >= 700000
ORDER BY
    T1.TOTAL_PRICE ASC